# Generated by Django 4.0.3 on 2022-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='img_up',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
